[package]
name = "write_summary"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.21"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
serde_json = "1.0.93"
snafu = "0.7"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
iox_time = { path = "../iox_time" }
