[package]
name = "compactor"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
async-trait = "0.1.64"
backoff = { path = "../backoff" }
bytes = "1.4"
data_types = { path = "../data_types" }
datafusion = { workspace = true }
futures = "0.3"
generated_types = { path = "../generated_types" }
iox_catalog = { path = "../iox_catalog" }
iox_query = { path = "../iox_query" }
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
object_store = "0.5.2"
observability_deps = { path = "../observability_deps" }
parquet_file = { path = "../parquet_file" }
predicate = { path = "../predicate" }
schema = { path = "../schema" }
service_grpc_catalog = { path = "../service_grpc_catalog"}
snafu = "0.7"
thiserror = "1.0"
tokio = { version = "1.25", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.4" }
tonic = { version = "0.8" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
iox_tests = { path = "../iox_tests" }
itertools = "0.10.5"
test_helpers = { path = "../test_helpers" }
