[package]
name = "test_helpers_end_to_end"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
assert_cmd = "2.0.7"
bytes = "1.3"
data_types = { path = "../data_types" }
futures = "0.3"
generated_types = { path = "../generated_types" }
http = "0.2.8"
hyper = "0.14"
influxdb_iox_client = { path = "../influxdb_iox_client", features = ["flight", "format"] }
nix = "0.26"
observability_deps = { path = "../observability_deps" }
once_cell = { version = "1.16.0", features = ["parking_lot"] }
parking_lot = "0.12"
prost = "0.11"
rand = "0.8.3"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls" , "postgres", "uuid" ] }
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
tokio = { version = "1.22", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = "0.7"
tonic = "0.8"
workspace-hack = { path = "../workspace-hack"}
