[package]
name = "iox_query"
description = "IOx Query Interface and Executor"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# This crate is designed to be independent of the rest of the IOx
# server and specific storage systems such as Mutable Buffer and Read Buffer.
#
# The rationale for this is to:
#
# 1. Keep change/compile/link time down during development when working on just this crate
# 2. Allow for query logic testing without bringing in all the storage systems.

[dependencies] # In alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
async-trait = "0.1"
chrono = { version = "0.4", default-features = false }
chrono-tz = { version = "0.8" }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
executor = { path = "../executor"}
futures = "0.3"
hashbrown = { workspace = true }
influxdb_influxql_parser = { path = "../influxdb_influxql_parser" }
itertools = "0.10.5"
once_cell = "1"
object_store = "0.5.4"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
query_functions = { path = "../query_functions"}
regex = "1"
schema = { path = "../schema" }
snafu = "0.7"
tokio = { version = "1.25", features = ["macros", "parking_lot"] }
tokio-stream = "0.1"
trace = { path = "../trace" }
predicate = { path = "../predicate" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
assert_matches = "1"
insta = { version = "1", features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
