[package]
name = "write_buffer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
data_types = { path = "../data_types" }
dml = { path = "../dml" }
dotenvy = "0.15.6"
futures = "0.3"
generated_types = { path = "../generated_types" }
hashbrown = { workspace = true }
http = "0.2"
httparse = "1.8"
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
mutable_batch_pb = { path = "../mutable_batch_pb" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
pin-project = "1.0"
prost = "0.11"
rskafka = { git = "https://github.com/influxdata/rskafka.git", rev="abb2a28cff5ce39d186e814a0c5012267b9690a4", default-features = false, features = ["compression-zstd", "transport-socks5"] }
schema = { path = "../schema" }
tokio = { version = "1.22", features = ["fs", "macros", "parking_lot", "rt", "sync", "time"] }
tokio-util = "0.7.4"
trace = { path = "../trace" }
trace_http = { path = "../trace_http" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers" }

[package.metadata.cargo-udeps.ignore]
# used within the `maybe_skip_kafka_integration` macro and cannot be detected by a normal analysis pass
normal = ["dotenvy"]
