[package]
name = "ingester"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow_util = { path = "../arrow_util" }
arrow-flight = { workspace = true }
async-trait = "0.1.60"
backoff = { path = "../backoff" }
bytes = "1.3"
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
dml = { path = "../dml" }
flatbuffers = "22.9.29"
futures = "0.3"
generated_types = { path = "../generated_types" }
hashbrown = { workspace = true }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
iox_query = { path = "../iox_query" }
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch"}
mutable_batch_lp = { path = "../mutable_batch_lp" }
object_store = "0.5.2"
observability_deps = { path = "../observability_deps" }
once_cell = "1"
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
pin-project = "1.0"
predicate = { path = "../predicate" }
prost = "0.11"
rand = "0.8.5"
schema = { path = "../schema" }
service_grpc_catalog = { path = "../service_grpc_catalog"}
snafu = "0.7"
thiserror = "1.0"
tokio = { version = "1.22", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.4" }
tonic = { version = "0.8" }
trace = { path = "../trace" }
tracker = { path = "../tracker" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}
write_buffer = { path = "../write_buffer" }
write_summary = { path = "../write_summary" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }

[dev-dependencies]
assert_matches = "1.5.0"
lazy_static = "1.4.0"
paste = "1.0.11"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
tokio-stream = {version = "0.1.11", default_features = false }
