[package]
name = "influxrpc_parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlparser = "0.30.0"
snafu = "0.7.4"

generated_types = { path = "../generated_types" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
