[package]
name = "sqlx-hotswap-pool"
description = "Workaround for the lack of dyanmic credential update support in sqlx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# Prevent this from being published to crates.io!
publish = false

[dependencies]
sqlx = { version = "0.6.1", features = ["runtime-tokio-rustls", "postgres", "json", "tls"] }
either = "1.8.1"
tokio = { version = "1.25", features = ["rt-multi-thread", "macros", "parking_lot"] }
futures = "0.3"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
dotenvy = "0.15.6"
rand = { version = "0.8", features = ["small_rng"] }
