[package]
name = "ioxd_ingest_replica"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1"
clap_blocks = { path = "../clap_blocks" }
hyper = "0.14"
ingest_replica = { path = "../ingest_replica" }
iox_catalog = { path = "../iox_catalog" }
iox_query = { version = "0.1.0", path = "../iox_query" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
parquet_file = { version = "0.1.0", path = "../parquet_file" }
thiserror = "1.0.38"
tokio = { version = "1.22", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = "0.7.4"
trace = { path = "../trace" }
workspace-hack = { path = "../workspace-hack"}
