[package]
name = "query_tests"
description = "Tests of the query engine against different database configurations"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow-flight = { workspace = true }
arrow_util = { path = "../arrow_util" }
async-trait = "0.1"
backoff = { path = "../backoff" }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
dml = { path = "../dml" }
futures = "0.3"
generated_types = { path = "../generated_types" }
hashbrown = { workspace = true }
influxdb_iox_client = { path = "../influxdb_iox_client" }
ingester = { path = "../ingester" }
iox_catalog = { path = "../iox_catalog" }
iox_query = { path = "../iox_query" }
iox_tests = { path = "../iox_tests" }
iox_time = { path = "../iox_time" }
itertools = "0.10"
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
once_cell = { version = "1.17", features = ["parking_lot"] }
parquet_file = { version = "0.1.0", path = "../parquet_file" }
predicate = { path = "../predicate" }
prost = { version = "0.11" }
querier = { path = "../querier" }
regex = "1.7.1"
schema = { path = "../schema" }
sharder = { path = "../sharder" }
tokio = { version = "1.25", features = ["macros", "parking_lot", "rt-multi-thread", "time"] }
trace = { path = "../trace" }
uuid = "1"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
insta = { version = "1", features = ["yaml", "serde"] }
snafu = "0.7"
tempfile = "3.1.0"
test_helpers = { path = "../test_helpers" }
