[package]
name = "ioxd_compactor"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
backoff = { path = "../backoff" }
clap_blocks = { path = "../clap_blocks" }
compactor = { path = "../compactor" }
data_types = { path = "../data_types" }
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
iox_query = { path = "../iox_query" }
object_store = "0.5.4"
iox_time = { path = "../iox_time" }
trace = { path = "../trace" }

# Crates.io dependencies, in alphabetical order
async-trait = "0.1"
hyper = "0.14"
thiserror = "1.0.38"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
parquet_file = { version = "0.1.0", path = "../parquet_file" }
tokio-util = "0.7.7"
