[package]
name = "parquet_to_line_protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
futures = {version = "0.3"}
num_cpus = "1.15.0"
object_store = { version = "0.5.4" }
parquet_file  = { path = "../parquet_file" }
schema = { path = "../schema" }
tokio = "1.25"
snafu = "0.7"
workspace-hack = { version = "0.1", path = "../workspace-hack" }


[dev-dependencies]
mutable_batch = { path = "../mutable_batch" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
