[package]
name = "influxdb_tsm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
integer-encoding = "3.0.4"
snafu = "0.7"
snap = "1.1.0"
observability_deps = { path = "../observability_deps" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
flate2 = "1.0"
hex = "0.4.2"
rand = "0.8.3"
test_helpers = { path = "../test_helpers" }
