[package]
name = "service_common"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1.60"
datafusion = { workspace = true }
iox_query = { path = "../iox_query" }
metric = { path = "../metric" }
parking_lot = "0.12"
predicate = { path = "../predicate" }
tonic = "0.8"
trace = { path = "../trace" }
tracker = { path = "../tracker" }
workspace-hack = { path = "../workspace-hack"}
