[package]
name = "tracker"
description = "Utilities for tracking resource utilisation within IOx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3"
hashbrown = { workspace = true }
lock_api = "0.4.9"
metric = { path = "../metric" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
pin-project = "1.0"
iox_time = { path = "../iox_time" }
tokio = { version = "1.25", features = ["macros", "parking_lot", "sync", "time"] }
tokio-util = { version = "0.7.7" }
trace = { path = "../trace"}
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
# Need the multi-threaded executor for testing
tokio = { version = "1.25", features = ["macros", "parking_lot", "rt-multi-thread", "time"] }
