[package]
name = "object_store_metrics"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1.64"
bytes = "1.4"
futures = "0.3"
iox_time = { version = "0.1.0", path = "../iox_time" }
metric = { version = "0.1.0", path = "../metric" }
object_store = "0.5.4"
pin-project = "1.0.12"
tokio = { version = "1.25", features = ["io-util"] }
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
dotenvy = "0.15.6"
snafu = "0.7"
tokio = { version = "1.25", features = ["macros", "io-util"] }
