[package]
name = "service_grpc_flight"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Workspace dependencies, in alphabetical order
arrow_util = { path = "../arrow_util" }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
generated_types = { path = "../generated_types" }
observability_deps = { path = "../observability_deps" }
prost-types = { version = "0.11", features = ["std"] }
iox_query = { path = "../iox_query" }
service_common = { path = "../service_common" }
trace = { path = "../trace"}
trace_http = { path = "../trace_http"}
tracker = { path = "../tracker" }

# Crates.io dependencies, in alphabetical order
arrow = { workspace = true, features = ["prettyprint"] }
bytes = "1.3"
futures = "0.3"
iox_arrow_flight = { path = "../iox_arrow_flight" }
pin-project = "1.0"
prost = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
snafu = "0.7"
tokio = { version = "1.22", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tonic = "0.8"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
metric = { path = "../metric" }
assert_matches = "1"
